apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample-app-frontend

resources:
  - base-manifests.yaml

configMapGenerator:
  - name: frontend-config
    files:
      - frontend-app.py
