apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend
  labels:
    app: frontend-app
spec:
  selector:
    matchLabels:
      app: frontend-app
  endpoints:
  - port: web
    path: /metrics
    interval: 10s
