apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample-app

resources:
  - base-manifests.yaml
  - networkpolicy.yaml
  - servicemonitor.yaml
  - prometheusrule.yaml
  - pdb.yaml

configMapGenerator:
  - name: app-config
    files:
      - backend-app.py
    options:
      disableNameSuffixHash: true
